Box content
ComicScrip/lyon-react-mars22-p2g1 pull request #54
Opened 2022-04-12 14:45 UTC by 01adrien

2022-04-14 14:35 UTC, PiDartevelle approved these changes

2022-04-14 14:38 UTC, PiDartevelle submitted a review, later dismissed

2022-04-15 12:22 UTC, NycoChavanoud requested changes
Quelques ajustements. Faire attention à ces détails à l'avenir...

2022-04-15 12:22 UTC, NycoChavanoud commented on src/box_detail_stuffs/components/AddBookForm.jsx
> +  const [NotFound, setBookNotFound] = useState(false);
pas de Majuscule sur la variable svp

2022-04-15 12:22 UTC, NycoChavanoud commented on src/box_detail_stuffs/components/Book.jsx
> +  const [isBorrow, setBorrow] = useState(borrowState);
pas dramatique mais 'isBorrow' // setIsBorrow serait plus logique que setBorrow ?

2022-04-15 12:22 UTC, NycoChavanoud commented on src/components/Header.jsx
> +const getActiveLinkStyle = ({ isActive }) => {
code mort = pas en prod svp

2022-04-15 12:22 UTC, NycoChavanoud commented on src/pages/BoxDetail.jsx
> +  const [booksList, setBook] = useState(booksDataBase);
setBook ? (setBookList)...

2022-04-18 16:43 UTC, ComicScrip commented on src/box_detail_stuffs/components/Book.jsx
> +  const [isBorrow, setBorrow] = useState(borrowState);
Je dirais même isBorrowed // setIsBorrowed :p

2022-04-18 19:38 UTC, closed without merging