Popup
ComicScrip/lyon-react-mars22-p2g1 pull request #56
Opened 2022-04-12 20:41 UTC by JenniferDELEO

2022-04-15 09:31 UTC, 01adrien submitted a review, later dismissed

2022-04-15 12:30 UTC, NycoChavanoud requested changes
quelques petits ajustements...

2022-04-15 12:30 UTC, NycoChavanoud commented on public/index.html
> +      content=""
content=""??????

2022-04-15 12:30 UTC, NycoChavanoud commented on src/components/Header.jsx
> +const getActiveLinkStyle = ({ isActive }) => {
code mort...

2022-04-15 13:07 UTC, PiDartevelle submitted a review, later dismissed

2022-04-18 16:40 UTC, ComicScrip commented on dist/output.css
> +/*
mettre `dist` dans le fichier `.gitignore` please

2022-04-19 12:56 UTC, merged