Map initialisation
ComicScrip/lyon-react-mars22-p2g1 pull request #60
Opened 2022-04-14 13:58 UTC by ClemMoFr

2022-04-14 15:19 UTC, GaspardMzt approved these changes

2022-04-14 15:22 UTC, GaspardMzt submitted a review, later dismissed

2022-04-15 12:39 UTC, NycoChavanoud requested changes

2022-04-15 12:39 UTC, NycoChavanoud commented on src/components/Header.jsx
> +const getActiveLinkStyle = ({ isActive }) => {
dead code

2022-04-15 13:19 UTC, GaspardMzt submitted a review, later dismissed

2022-04-18 16:29 UTC, ComicScrip commented
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16140010/163839968-48b80357-ee7f-4ea7-bea7-c98045a16eb6.png">

2022-04-19 12:23 UTC, GaspardMzt submitted a review, later dismissed

2022-04-21 14:13 UTC, GaspardMzt approved these changes

2022-04-21 14:21 UTC, ComicScrip submitted a review, later dismissed

2022-04-21 14:22 UTC, merged