Contact component
ComicScrip/lyon-react-mars22-p2g1 pull request #77
Opened 2022-04-20 12:04 UTC by PiDartevelle

2022-04-20 14:33 UTC, JenniferDELEO submitted a review, later dismissed

2022-04-21 08:08 UTC, ComicScrip requested changes

2022-04-21 08:08 UTC, ComicScrip commented on package.json
> +  "rnpm": {
enelever svp

2022-04-21 08:08 UTC, ComicScrip commented on src/assets/fonts/OFL.txt
> +Copyright 2020 The Poppins Project Authors (https://github.com/itfoundry/Poppins)
a enlever

2022-04-21 12:40 UTC, ComicScrip approved these changes

2022-04-21 12:40 UTC, merged