Mise en page (sauf bouton vérifier disponibilité)
ComicScrip/lyon-react-mars22-p2g1 pull request #97
Opened 2022-04-28 08:36 UTC by GaspardMzt

2022-04-28 14:59 UTC, JenniferDELEO submitted a review, later dismissed

2022-04-28 15:21 UTC, ComicScrip requested changes

2022-04-28 15:21 UTC, ComicScrip commented on src/pages/BookDetail.jsx
> +  const id = useParams();
`const {id} = useParams()`

2022-04-29 07:48 UTC, JenniferDELEO approved these changes

2022-04-29 07:51 UTC, ComicScrip approved these changes

2022-04-29 07:51 UTC, merged